const ConfigTypes = {
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  CLEAR_SEARCH_TEXT: "CLEAR_SEARCH_TEXT",
  ADD_TAG: "ADD_TAG",
  REMOVE_TAG: "REMOVE_TAG",
  TOGGLE_SORT_ORDER: "TOGGLE_SORT_ORDER"
};

export default ConfigTypes;
